version: "3.0"
services:
  nats:
    image: mheers/nats-auto-server:2.10.22-alpine3.20
    restart: unless-stopped
    volumes:
      - "./data/nats/:/data"
      - ./config/mq/additional.conf:/nats/conf/additional.conf:ro
    ports:
      - 127.0.0.1:9222:9222 # proxy this to 4443 and add tls certificates on the proxy!
      - 4222:4222 # only for 'internal' communication
    environment:
      - OPERATOR_SEED=${OPERATOR_SEED}
      - SYS_ACCOUNT_SEED=${SYS_ACCOUNT_SEED}
      - ACCOUNT_SEED=${ACCOUNT_SEED}
      # - TLS=true # enable this when to use nats internal tls termination (needs to have a ./server-cert.pem mounted)
